# Generated by Django 4.1 on 2022-09-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=128)),
                ('fechaCreacion', models.CharField(default='', max_length=128)),
                ('usuarioResponsable', models.CharField(default='', max_length=128)),
                ('estadoTarea', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='usuariosRegistrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=128)),
                ('apellido', models.CharField(default='', max_length=128)),
                ('password', models.CharField(default='', max_length=128)),
                ('codigoUsuario', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
