# Generated by Django 4.1 on 2022-09-07 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupoEstudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='fechaEntrega',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estadoTarea',
            field=models.CharField(default='PROGRESO', max_length=128),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fechaCreacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
