# Generated by Django 4.1 on 2022-09-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0002_grupoestudiantes_tarea_fechaentrega_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='grupoEstudiantes',
        ),
    ]
