# Generated by Django 4.1 on 2022-09-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0003_delete_grupoestudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechaEntrega',
            field=models.DateField(default='0'),
        ),
    ]
